### ISSUE TITLE
Allow specifying codecs per service instead of transcoder

### ISSUE THREAD

**Issue by rauanmayemir** [connectrpc/vanguard-go#142]
I wanted to draw a parallel between envoy `grpc_json_transcoder` filter and vanguard.
I can stack several envoy filters with their own set of services and options. E.g:

```yaml
http_filters:
- name: envoy.filters.http.grpc_json_transcoder
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
    proto_descriptor: "proto1.pb"
    services:
      - package.v1.Service1
    match_incoming_request_route: true
    ignore_unknown_query_parameters: true
    print_options:
      add_whitespace: true
      always_print_primitive_fields: false
      always_print_enums_as_ints: false
      preserve_proto_field_names: true # use field names as is
    convert_grpc_status: true
- name: envoy.filters.http.grpc_json_transcoder
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
    proto_descriptor: "proto2.pb"
    services:
      - package.v1.Service2
    match_incoming_request_route: true
    ignore_unknown_query_parameters: true
    print_options:
      add_whitespace: true
      always_print_primitive_fields: false
      always_print_enums_as_ints: false
      preserve_proto_field_names: false # do not use field names, camelize or use json_name instead
    convert_grpc_status: true
```

So vanguard transcoder aligns well with an envoy transcoder filter.

However, I'm not sure it makes sense to apply multiple vanguard transcoders and chain them.
Would it be better to allow using a single transcoder and rather allow specifying more ServiceOption's, tweaking them per service?

For the particular case above, we don't want to use proto field_names in `package.v1.Service2`, but rather set customized json_name's. This is usually useful when we need to map our transcoded service to an already established json schema.

For this to work with a single vanguard transcoder, we'd need to be able to specify not just codec name, but also options per service. I see that `vanguard.WithTargetCodecs` already sets up codeNames map, but it's an empty map. Is it stubbed to potentially allow options in future?
